# Generated by Django 4.2.13 on 2024-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDictField',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('name', models.CharField(max_length=64, verbose_name='字段名称')),
                ('type', models.PositiveIntegerField(choices=[(1, '文字'), (2, '段落'), (3, '多段段落'), (4, '图片')], verbose_name='字段类型')),
                ('ident', models.CharField(max_length=64, verbose_name='字段标识')),
                ('status', models.BooleanField(default=False, verbose_name='字段启用状态')),
                ('text', models.TextField(blank=True, null=True, verbose_name='字段的值')),
                ('pic', models.ImageField(blank=True, null=True, upload_to='field_images', verbose_name='图片信息')),
            ],
            options={
                'verbose_name': '用户字段表',
                'verbose_name_plural': '用户字段表',
                'db_table': 'user_dict_for_generate_doc',
                'ordering': ('-create_datetime', '-id'),
            },
        ),
    ]
