# Generated by Django 4.2.3 on 2023-07-25 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dict',
            options={'ordering': ('-create_datetime',), 'verbose_name': '字典表', 'verbose_name_plural': '字典表'},
        ),
        migrations.AlterModelOptions(
            name='dictitem',
            options={'ordering': ('-create_datetime',), 'verbose_name': '字典表item表', 'verbose_name_plural': '字典表item表'},
        ),
    ]
