# Generated by Django 4.2.3 on 2023-08-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0002_alter_dict_options_alter_dictitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dict',
            name='status',
            field=models.CharField(blank=True, default='1', help_text='状态', max_length=8, null=True, verbose_name='状态'),
        ),
    ]
