# Generated by Django 4.2.13 on 2024-07-25 18:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_design_protocal'),
        ('dict', '0003_fragment_picturefield_tablefield_textfield_wordfield_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefield',
            name='frag',
        ),
        migrations.RemoveField(
            model_name='textfield',
            name='frag',
        ),
        migrations.RemoveField(
            model_name='wordfield',
            name='frag',
        ),
        migrations.RemoveField(
            model_name='fragment',
            name='field_seq',
        ),
        migrations.AddField(
            model_name='fragment',
            name='content',
            field=tinymce.models.HTMLField(blank=True, help_text='文档片段的富文本', null=True, verbose_name='片段富文本'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='belong_doc',
            field=models.PositiveSmallIntegerField(choices=[(1, 'dg'), (2, 'sm'), (3, 'jl'), (4, 'hsm'), (5, 'hjl'), (6, 'bg'), (7, 'wtd')], verbose_name='所属文档'),
        ),
        migrations.AlterField(
            model_name='fragment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frag', related_query_name='qFrag', to='project.project'),
        ),
        migrations.DeleteModel(
            name='PictureField',
        ),
        migrations.DeleteModel(
            name='TableField',
        ),
        migrations.DeleteModel(
            name='TextField',
        ),
        migrations.DeleteModel(
            name='WordField',
        ),
    ]
