# Generated by Django 4.2.16 on 2024-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0004_remove_tablefield_frag_remove_textfield_frag_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fragment',
            name='unique_name_belong_doc',
        ),
        migrations.AddConstraint(
            model_name='fragment',
            constraint=models.UniqueConstraint(fields=('name', 'belong_doc', 'project_id'), name='unique_name_belong_doc'),
        ),
    ]
