# Generated by Django 4.2.3 on 2023-08-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0005_alter_dictitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictitem',
            name='show_title',
            field=models.CharField(blank=True, help_text='类型转文字', max_length=64, null=True, verbose_name='类型转文字'),
        ),
    ]
