# Generated by Django 4.2.3 on 2023-08-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0006_dictitem_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictitem',
            name='show_title',
            field=models.CharField(blank=True, default='', help_text='类型转文字', max_length=64, verbose_name='类型转文字'),
            preserve_default=False,
        ),
    ]
