# Generated by Django 4.2.3 on 2023-10-07 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0007_alter_dictitem_show_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictitem',
            name='doc_name',
            field=models.CharField(blank=True, help_text='文档名称', max_length=64, null=True, verbose_name='文档名称'),
        ),
        migrations.AddField(
            model_name='dictitem',
            name='ident_and_version',
            field=models.CharField(blank=True, help_text='标识/版本', max_length=64, null=True, verbose_name='标识/版本'),
        ),
        migrations.AddField(
            model_name='dictitem',
            name='publish_date',
            field=models.CharField(blank=True, help_text='发布日期', max_length=64, null=True, verbose_name='发布日期'),
        ),
        migrations.AddField(
            model_name='dictitem',
            name='source',
            field=models.CharField(blank=True, help_text='来源', max_length=32, null=True, verbose_name='来源'),
        ),
    ]
