# Generated by Django 4.2.3 on 2023-10-07 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0008_dictitem_doc_name_dictitem_ident_and_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictitem',
            name='ident_and_version',
        ),
    ]
