from .settings import *

# ~~~~这部分是延用settings.py，注意在settings统一修改~~~~
BASE_DIR = BASE_DIR
SECRET_KEY = SECRET_KEY
INSTALLED_APPS = INSTALLED_APPS
MIDDLEWARE = MIDDLEWARE
SECURE_CROSS_ORIGIN_OPENER_POLICY = SECURE_CROSS_ORIGIN_OPENER_POLICY
ROOT_URLCONF = ROOT_URLCONF
TEMPLATES = TEMPLATES
WSGI_APPLICATION = WSGI_APPLICATION
CACHES = CACHES
LANGUAGE_CODE = LANGUAGE_CODE
TIME_ZONE = TIME_ZONE
USE_I18N = USE_I18N
USE_TZ = USE_TZ
DEFAULT_AUTO_FIELD = DEFAULT_AUTO_FIELD
TOKEN_LIFETIME = TOKEN_LIFETIME
AUTH_USER_MODEL = AUTH_USER_MODEL
USERNAME_FIELD = USERNAME_FIELD
NINJA_JWT = NINJA_JWT
ALLOWED_HOSTS = ALLOWED_HOSTS
STATIC_URL = STATIC_URL
STATIC_ROOT = STATIC_ROOT
MEDIA_URL = MEDIA_URL
MEDIA_ROOT = MEDIA_ROOT
API_LOG_ENABLE = API_LOG_ENABLE
API_LOG_METHODS = API_LOG_METHODS
API_MODEL_MAP = API_MODEL_MAP
API_OPERATION_EXCLUDE_START = API_OPERATION_EXCLUDE_START
DATA_UPLOAD_MAX_MEMORY_SIZE = DATA_UPLOAD_MAX_MEMORY_SIZE

# ~~~~下面都是开发环境的配置~~~~
# 调试模式【开发环境有变动】
DEBUG = True

# Mysql数据库【开发环境有变动】
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": DATABASE_HOST,
        "PORT": 3306,
        "USER": DATABASE_USER,
        "PASSWORD": DATABASE_PASSWORD,
        "NAME": DATABASE_NAME,
    }
}
