# Generated by Django 4.2.13 on 2024-07-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
