# Generated by Django 4.2.3 on 2023-07-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('ident', models.CharField(blank=True, help_text='项目标识', max_length=64, null=True, verbose_name='项目标识')),
                ('name', models.CharField(blank=True, help_text='项目名称', max_length=100, null=True, verbose_name='项目名称')),
                ('engin_model', models.CharField(blank=True, help_text='工程型号', max_length=64, null=True, verbose_name='工程型号')),
                ('section_system', models.CharField(blank=True, help_text='分系统', max_length=64, null=True, verbose_name='分系统')),
                ('sub_system', models.CharField(blank=True, help_text='子系统', max_length=64, null=True, verbose_name='子系统')),
                ('device', models.CharField(blank=True, help_text='设备', max_length=64, null=True, verbose_name='设备')),
                ('beginTime', models.DateField(auto_now_add=True, help_text='开始时间', null=True, verbose_name='开始时间')),
                ('endTime', models.DateField(auto_now_add=True, help_text='结束时间', null=True, verbose_name='结束时间')),
                ('duty_person', models.CharField(help_text='负责人', max_length=64, verbose_name='负责人')),
                ('member', models.JSONField(blank=True, default=[], help_text='项目成员', null=True, verbose_name='项目成员')),
                ('security_level', models.CharField(blank=True, help_text='安全等级', max_length=8, null=True, verbose_name='安全等级')),
                ('test_level', models.JSONField(blank=True, default=[], help_text='测试级别', null=True, verbose_name='测试级别')),
                ('plant_type', models.CharField(blank=True, help_text='平台类型', max_length=64, null=True, verbose_name='平台类型')),
                ('report_type', models.CharField(blank=True, help_text='报告类型', max_length=64, null=True, verbose_name='报告类型')),
                ('language', models.JSONField(blank=True, default=[], help_text='被测语言', null=True, verbose_name='被测语言')),
                ('standard', models.JSONField(blank=True, default=[], help_text='依据标准', null=True, verbose_name='依据标准')),
                ('entrust_ident', models.CharField(blank=True, help_text='委托方标识', max_length=64, null=True, verbose_name='委托方标识')),
                ('entrust_legal', models.CharField(blank=True, help_text='委托方法人', max_length=64, null=True, verbose_name='委托方法人')),
                ('entrust_contact', models.CharField(blank=True, help_text='委托方联系人', max_length=64, null=True, verbose_name='委托方联系人')),
                ('entrust_contact_phone', models.CharField(blank=True, help_text='委托方电话', max_length=64, null=True, verbose_name='委托方电话')),
                ('entrust_email', models.CharField(blank=True, help_text='委托方邮箱', max_length=64, null=True, verbose_name='委托方邮箱')),
                ('dev_ident', models.CharField(blank=True, help_text='研制方标识', max_length=64, null=True, verbose_name='研制方标识')),
                ('dev_legal', models.CharField(blank=True, help_text='研制方法人', max_length=64, null=True, verbose_name='研制方法人')),
                ('dev_contact', models.CharField(blank=True, help_text='研制方联系人', max_length=64, null=True, verbose_name='研制方联系人')),
                ('dev_contact_phone', models.CharField(blank=True, help_text='研制方电话', max_length=64, null=True, verbose_name='研制方电话')),
                ('dev_email', models.CharField(blank=True, help_text='研制方邮箱', max_length=64, null=True, verbose_name='研制方邮箱')),
                ('test_ident', models.CharField(blank=True, help_text='测评中心标识', max_length=64, null=True, verbose_name='测评中心标识')),
                ('test_legal', models.CharField(blank=True, help_text='测评中心法人', max_length=64, null=True, verbose_name='测评中心法人')),
                ('test_contact', models.CharField(blank=True, help_text='测评中心联系人', max_length=64, null=True, verbose_name='测评中心联系人')),
                ('test_contact_phone', models.CharField(blank=True, help_text='测评中心电话', max_length=64, null=True, verbose_name='测评中心电话')),
                ('test_email', models.CharField(blank=True, help_text='测评中心邮箱', max_length=64, null=True, verbose_name='测评中心邮箱')),
                ('step', models.CharField(blank=True, help_text='项目阶段', max_length=8, null=True, verbose_name='项目阶段')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'project_project',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
