# Generated by Django 4.2.3 on 2023-07-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_round'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ('key',), 'verbose_name': '轮次信息', 'verbose_name_plural': '轮次信息'},
        ),
        migrations.CreateModel(
            name='Dut',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('ident', models.CharField(blank=True, help_text='被测件标识', max_length=64, null=True, verbose_name='被测件标识')),
                ('type', models.CharField(blank=True, help_text='被测件类型', max_length=16, null=True, verbose_name='被测件类型')),
                ('name', models.CharField(blank=True, help_text='被测件名称', max_length=64, null=True, verbose_name='被测件名称')),
                ('black_line', models.CharField(blank=True, help_text='空行代码数', max_length=64, null=True, verbose_name='空行代码数')),
                ('pure_code_line', models.CharField(blank=True, help_text='代码行数', max_length=64, null=True, verbose_name='代码行数')),
                ('mix_line', models.CharField(blank=True, help_text='混合行数', max_length=64, null=True, verbose_name='混合行数')),
                ('total_comment_line', models.CharField(blank=True, help_text='总注释行', max_length=64, null=True, verbose_name='总注释行')),
                ('total_code_line', models.CharField(blank=True, help_text='总代码行', max_length=64, null=True, verbose_name='总代码行')),
                ('total_line', models.CharField(blank=True, help_text='总行数', max_length=64, null=True, verbose_name='总行数')),
                ('comment_line', models.CharField(blank=True, help_text='注释率', max_length=64, null=True, verbose_name='注释率')),
                ('title', models.CharField(blank=True, help_text='树-名称', max_length=64, null=True, verbose_name='树-名称')),
                ('key', models.CharField(blank=True, help_text='树-key', max_length=64, null=True, verbose_name='树-key')),
                ('level', models.CharField(blank=True, default=1, help_text='树-level', max_length=64, null=True, verbose_name='树-level')),
                ('project', models.ForeignKey(db_constraint=False, help_text='归属项目', on_delete=django.db.models.deletion.CASCADE, related_name='pdField', related_query_name='pdQuery', to='project.project', verbose_name='归属项目')),
                ('round', models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='rdField', related_query_name='rdQuery', to='project.round', verbose_name='归属轮次')),
            ],
            options={
                'verbose_name': '被测件信息',
                'verbose_name_plural': '被测件信息',
                'db_table': 'project_dut',
                'ordering': ('key',),
            },
        ),
    ]
