# Generated by Django 4.2.13 on 2024-07-23 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_contact_refer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='protocal',
            field=models.CharField(blank=True, default='', help_text='接口数据', max_length=64, null=True, verbose_name='接口数据'),
        ),
    ]
