# Generated by Django 4.2.3 on 2023-07-31 11:23

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_round_options_dut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('ident', models.CharField(blank=True, help_text='测试需求标识', max_length=64, null=True, verbose_name='测试需求标识')),
                ('name', models.CharField(blank=True, help_text='测试需求名称', max_length=64, null=True, verbose_name='测试需求名称')),
                ('demandType', models.CharField(blank=True, help_text='测试需求类型', max_length=8, null=True, verbose_name='测试需求类型')),
                ('description', tinymce.models.HTMLField(blank=True, help_text='测试需求描述', null=True, verbose_name='测试需求描述')),
                ('title', models.CharField(blank=True, help_text='树-名称', max_length=64, null=True, verbose_name='树-名称')),
                ('key', models.CharField(blank=True, help_text='round-dut-designkey', max_length=64, null=True, verbose_name='round-dut-designkey')),
                ('level', models.CharField(blank=True, default=2, help_text='树-level', max_length=64, null=True, verbose_name='树-level')),
                ('dut', models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='rsField', related_query_name='rsQuery', to='project.dut', verbose_name='归属轮次')),
                ('project', models.ForeignKey(db_constraint=False, help_text='归属项目', on_delete=django.db.models.deletion.CASCADE, related_name='psField', related_query_name='psQuery', to='project.project', verbose_name='归属项目')),
                ('round', models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='rsField', related_query_name='rsQuery', to='project.round', verbose_name='归属轮次')),
            ],
            options={
                'verbose_name': '测试需求',
                'verbose_name_plural': '测试需求',
                'db_table': 'project_design',
                'ordering': ('key',),
            },
        ),
    ]
