# Generated by Django 4.2.15 on 2024-09-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_design_protocal'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='secret',
            field=models.CharField(default='1', help_text='密级', max_length=30, verbose_name='密级'),
        ),
    ]
