# Generated by Django 4.2.3 on 2023-08-01 11:48

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_design'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestDemand',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('ident', models.CharField(blank=True, help_text='测试需求标识', max_length=64, null=True, verbose_name='测试需求标识')),
                ('name', models.CharField(blank=True, help_text='测试需求名称', max_length=64, null=True, verbose_name='测试需求名称')),
                ('adequacy', models.CharField(blank=True, help_text='充分条件', max_length=128, null=True, verbose_name='充分条件')),
                ('termination', models.CharField(blank=True, help_text='终止条件', max_length=64, null=True, verbose_name='终止条件')),
                ('premise', models.CharField(blank=True, help_text='前提', max_length=64, null=True, verbose_name='前提')),
                ('priority', models.CharField(blank=True, help_text='优先级', max_length=8, null=True, verbose_name='优先级')),
                ('testType', models.JSONField(blank=True, default=[], help_text='测试类型', null=True, verbose_name='测试类型')),
                ('testMethod', models.CharField(blank=True, help_text='测试方法', max_length=512, null=True, verbose_name='测试方法')),
                ('title', models.CharField(blank=True, help_text='树-名称', max_length=64, null=True, verbose_name='树-名称')),
                ('key', models.CharField(blank=True, help_text='round-dut-designkey-testdemand', max_length=64, null=True, verbose_name='round-dut-designkey-testdemand')),
                ('level', models.CharField(blank=True, default=3, help_text='树-level', max_length=64, null=True, verbose_name='树-level')),
            ],
            options={
                'verbose_name': '核心模型',
                'verbose_name_plural': '核心模型',
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='design',
            name='demandType',
            field=models.CharField(blank=True, help_text='设计需求类型', max_length=8, null=True, verbose_name='设计需求类型'),
        ),
        migrations.AlterField(
            model_name='design',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='设计需求描述', null=True, verbose_name='设计需求描述'),
        ),
        migrations.AlterField(
            model_name='design',
            name='ident',
            field=models.CharField(blank=True, help_text='设计需求标识', max_length=64, null=True, verbose_name='设计需求标识'),
        ),
        migrations.AlterField(
            model_name='design',
            name='name',
            field=models.CharField(blank=True, help_text='设计需求名称', max_length=64, null=True, verbose_name='设计需求名称'),
        ),
        migrations.CreateModel(
            name='TestDemandContent',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('testXuQiu', models.CharField(blank=True, help_text='测试需求条目', max_length=1024, null=True, verbose_name='测试需求条目')),
                ('testYuQi', models.CharField(blank=True, help_text='测试需求条目的预期', max_length=1024, null=True, verbose_name='测试需求条目的预期')),
                ('testDemand', models.ForeignKey(db_constraint=False, help_text='归属的测试项', on_delete=django.db.models.deletion.CASCADE, related_name='testQField', related_query_name='testQField', to='project.testdemand', verbose_name='归属的测试项')),
            ],
            options={
                'verbose_name': '核心模型',
                'verbose_name_plural': '核心模型',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='testdemand',
            name='design',
            field=models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='dtField', related_query_name='dtQuery', to='project.design', verbose_name='归属轮次'),
        ),
        migrations.AddField(
            model_name='testdemand',
            name='dut',
            field=models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='dutField', related_query_name='dtQuery', to='project.dut', verbose_name='归属轮次'),
        ),
        migrations.AddField(
            model_name='testdemand',
            name='project',
            field=models.ForeignKey(db_constraint=False, help_text='归属项目', on_delete=django.db.models.deletion.CASCADE, related_name='ptField', related_query_name='ptQuery', to='project.project', verbose_name='归属项目'),
        ),
        migrations.AddField(
            model_name='testdemand',
            name='round',
            field=models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='rtField', related_query_name='dutQuery', to='project.round', verbose_name='归属轮次'),
        ),
    ]
