# Generated by Django 4.2.15 on 2024-09-04 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casestep',
            name='status',
        ),
    ]
