# Generated by Django 4.2.19 on 2025-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_remove_casestep_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdemand',
            name='testDesciption',
            field=models.CharField(blank=True, default='', help_text='老版本-测试项描述', max_length=1024, null=True, verbose_name='测试项描述'),
        ),
    ]
