# Generated by Django 5.2 on 2025-04-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_testdemand_testdesciption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='grade',
            field=models.CharField(blank=True, default='1', help_text='等级', max_length=64, null=True, verbose_name='等级'),
        ),
    ]
