# Generated by Django 4.2.3 on 2023-08-02 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_testdemand_testtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdemand',
            name='termination',
            field=models.CharField(blank=True, help_text='终止条件', max_length=1024, null=True, verbose_name='终止条件'),
        ),
    ]
