# Generated by Django 4.2.3 on 2023-08-02 12:47

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_testdemand_termination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('ident', models.CharField(blank=True, help_text='用例标识', max_length=64, null=True, verbose_name='用例标识')),
                ('name', models.CharField(blank=True, help_text='用例名称', max_length=64, null=True, verbose_name='用例名称')),
                ('initialization', models.CharField(blank=True, help_text='用例名称', max_length=128, null=True, verbose_name='初始条件')),
                ('premise', models.CharField(blank=True, help_text='前提和约束', max_length=128, null=True, verbose_name='前提和约束')),
                ('summarize', models.CharField(blank=True, help_text='用例综述', max_length=256, null=True, verbose_name='用例综述')),
                ('designPerson', models.CharField(blank=True, help_text='设计人员', max_length=16, null=True, verbose_name='设计人员')),
                ('testPerson', models.CharField(blank=True, help_text='测试人员', max_length=16, null=True, verbose_name='测试人员')),
                ('monitorPerson', models.CharField(blank=True, help_text='审核人员', max_length=16, null=True, verbose_name='审核人员')),
                ('title', models.CharField(blank=True, help_text='树-名称', max_length=64, null=True, verbose_name='树-名称')),
                ('key', models.CharField(blank=True, help_text='round-dut-designkey-testdemand-case', max_length=64, null=True, verbose_name='round-dut-designkey-testdemand-case')),
                ('level', models.CharField(blank=True, default=4, help_text='树-level', max_length=64, null=True, verbose_name='树-level')),
                ('design', models.ForeignKey(db_constraint=False, help_text='归属设计需求', on_delete=django.db.models.deletion.CASCADE, related_name='dcField', related_query_name='dcQuery', to='project.design', verbose_name='归属设计需求')),
                ('dut', models.ForeignKey(db_constraint=False, help_text='归属被测件', on_delete=django.db.models.deletion.CASCADE, related_name='ducField', related_query_name='ducQuery', to='project.dut', verbose_name='归属被测件')),
                ('project', models.ForeignKey(db_constraint=False, help_text='归属项目', on_delete=django.db.models.deletion.CASCADE, related_name='pcField', related_query_name='pcQuery', to='project.project', verbose_name='归属项目')),
                ('round', models.ForeignKey(db_constraint=False, help_text='归属轮次', on_delete=django.db.models.deletion.CASCADE, related_name='rcField', related_query_name='rcQuery', to='project.round', verbose_name='归属轮次')),
                ('test', models.ForeignKey(db_constraint=False, help_text='归属测试需求', on_delete=django.db.models.deletion.CASCADE, related_name='tcField', related_query_name='tcQuery', to='project.testdemand', verbose_name='归属测试需求')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'project_case',
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='caseStep',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('operation', tinymce.models.HTMLField(blank=True, help_text='测试步骤-操作', null=True, verbose_name='测试步骤-操作')),
                ('expect', models.CharField(blank=True, help_text='用例预期', max_length=64, null=True, verbose_name='用例预期')),
                ('result', tinymce.models.HTMLField(blank=True, help_text='测试步骤-结果', null=True, verbose_name='测试步骤-结果')),
                ('passed', models.CharField(blank=True, default='3', help_text='是否通过', max_length=8, null=True, verbose_name='是否通过')),
                ('status', models.CharField(blank=True, default='3', help_text='执行状态', max_length=8, null=True, verbose_name='执行状态')),
                ('case', models.ForeignKey(db_constraint=False, help_text='归属的测试用例', on_delete=django.db.models.deletion.CASCADE, related_name='step', related_query_name='stepQ', to='project.case', verbose_name='归属的测试用例')),
            ],
            options={
                'verbose_name': '核心模型',
                'verbose_name_plural': '核心模型',
                'abstract': False,
            },
        ),
    ]
