# Generated by Django 5.2 on 2025-04-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_round_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='device',
        ),
        migrations.RemoveField(
            model_name='project',
            name='engin_model',
        ),
        migrations.RemoveField(
            model_name='project',
            name='section_system',
        ),
        migrations.RemoveField(
            model_name='project',
            name='sub_system',
        ),
    ]
