# Generated by Django 5.2 on 2025-04-16 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_project_device_remove_project_engin_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='package',
        ),
        migrations.RemoveField(
            model_name='round',
            name='speedGrade',
        ),
    ]
