# Generated by Django 5.2 on 2025-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_remove_round_package_remove_round_speedgrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testdemandcontent',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='testdemandcontent',
            name='observe',
        ),
        migrations.RemoveField(
            model_name='testdemandcontent',
            name='subDesc',
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='testDesciption',
            field=models.CharField(blank=True, default='', help_text='测试项描述', max_length=1024, null=True, verbose_name='测试项描述'),
        ),
    ]
