# Generated by Django 4.2.3 on 2023-08-16 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_problem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='plant_type',
            field=models.JSONField(blank=True, default=[], help_text='平台类型', null=True, verbose_name='平台类型'),
        ),
    ]
