# Generated by Django 5.2 on 2025-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_testdemandcontent_expect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='ident',
            field=models.CharField(blank=True, help_text='项目标识', max_length=64, null=True, unique=True, verbose_name='项目标识'),
        ),
    ]
