# Generated by Django 4.2.3 on 2023-08-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_remove_project_dev_ident_remove_project_dev_legal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('key', models.IntegerField(auto_created=True, help_text='公司名称', verbose_name='公司名称')),
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('entrust_person', models.CharField(blank=True, help_text='法人', max_length=16, verbose_name='法人')),
                ('name', models.CharField(blank=True, help_text='公司名称', max_length=64, verbose_name='公司名称')),
            ],
            options={
                'verbose_name': '委托方、研制方、测试方信息',
                'verbose_name_plural': '委托方、研制方、测试方信息',
                'db_table': 'contact_gongsi',
                'ordering': ('create_datetime',),
            },
        ),
    ]
