# Generated by Django 5.2 on 2025-04-24 11:01

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_alter_project_ident'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='timing_diagram',
            field=tinymce.models.HTMLField(blank=True, help_text='FPGA时序图', null=True, verbose_name='FPGA时序图'),
        ),
    ]
