# Generated by Django 4.2.3 on 2023-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='dev_unit',
            field=models.CharField(default='', help_text='开发方单位', max_length=64, verbose_name='开发方单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='entrust_unit',
            field=models.CharField(default='', help_text='委托方单位', max_length=64, verbose_name='委托方单位'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='test_unit',
            field=models.CharField(default='', help_text='测试方单位', max_length=64, verbose_name='测试方单位'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='key',
            field=models.IntegerField(auto_created=True, help_text='公司编号', verbose_name='公司编号'),
        ),
    ]
