# Generated by Django 5.2 on 2025-04-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_case_timing_diagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestep',
            name='expect',
            field=models.CharField(blank=True, help_text='用例预期', max_length=3072, null=True, verbose_name='用例预期'),
        ),
    ]
