# Generated by Django 5.2 on 2025-04-28 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_alter_casestep_expect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dut',
            name='black_line',
        ),
        migrations.RemoveField(
            model_name='dut',
            name='code_line',
        ),
        migrations.RemoveField(
            model_name='dut',
            name='comment_line',
        ),
        migrations.RemoveField(
            model_name='dut',
            name='mix_line',
        ),
        migrations.AddField(
            model_name='dut',
            name='comment_lines',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='注释行数'),
        ),
        migrations.AddField(
            model_name='dut',
            name='effective_lines',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='有效代码行数'),
        ),
        migrations.AddField(
            model_name='dut',
            name='total_lines',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='总行数'),
        ),
    ]
