# Generated by Django 4.2.3 on 2023-08-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_design_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdemand',
            name='testMethod',
            field=models.JSONField(blank=True, default=[], help_text='测试方法', verbose_name='测试方法'),
        ),
    ]
