# Generated by Django 5.2 on 2025-04-28 15:25

import django.db.models.deletion
import shortuuidfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_dut_black_line_remove_dut_code_line_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutMetrics',
            fields=[
                ('id', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, help_text='id', max_length=22, primary_key=True, serialize=False, verbose_name='id')),
                ('avg_function_lines', models.IntegerField(verbose_name='平均模块大小')),
                ('avg_cyclomatic', models.IntegerField(verbose_name='平均圈复杂度')),
                ('avg_fan_out', models.IntegerField(verbose_name='平均扇出数')),
                ('function_count', models.IntegerField(verbose_name='模块数量')),
                ('max_cyclomatic', models.IntegerField(verbose_name='最大圈复杂度')),
                ('high_cyclomatic_ratio', models.IntegerField(verbose_name='圈复杂度>20模块占比')),
                ('total_blanks', models.IntegerField(verbose_name='空行数')),
                ('dut', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', related_query_name='metrics', to='project.dut', verbose_name='归属源代码被测件')),
            ],
        ),
    ]
