# Generated by Django 5.2.3 on 2025-06-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_dutmetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdemandcontentstep',
            name='id',
            field=models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
