# Generated by Django 4.2.3 on 2023-08-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_testdemand_testmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='config_person',
            field=models.CharField(default='', help_text='配置管理员', max_length=64, verbose_name='配置管理员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='quality_person',
            field=models.CharField(default='', help_text='质量保证员', max_length=64, verbose_name='质量保证员'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='vise_person',
            field=models.CharField(default='', help_text='质量监督员', max_length=64, verbose_name='质量监督员'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='adequacy',
            field=models.CharField(blank=True, help_text='充分条件', max_length=256, null=True, verbose_name='充分条件'),
        ),
        migrations.AlterField(
            model_name='testdemand',
            name='premise',
            field=models.CharField(blank=True, help_text='前提', max_length=256, null=True, verbose_name='前提'),
        ),
    ]
