# Generated by Django 6.0 on 2025-12-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_alter_testdemandcontentstep_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdemandcontent',
            name='subDescription',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='测试子项一句话描述'),
        ),
    ]
