# Generated by Django 4.2.3 on 2023-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_project_config_person_project_quality_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='addr',
            field=models.CharField(blank=True, help_text='公司地址', max_length=64, verbose_name='公司地址'),
        ),
    ]
