# Generated by Django 6.0.2 on 2026-02-04 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_projectsoftsummary_stuctsortdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuctsortdata',
            name='project',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_schemas', to='project.project', verbose_name='该接口图所属的项目'),
        ),
        migrations.AlterField(
            model_name='stuctsortdata',
            name='soft_summary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_schemas', to='project.projectsoftsummary', verbose_name='所属软件概述'),
        ),
    ]
