# Generated by Django 6.0.2 on 2026-02-04 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_stuctsortdata_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuctsortdata',
            name='project',
            field=models.OneToOneField(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_schemas', to='project.project', verbose_name='该接口图所属的项目'),
        ),
    ]
