# Generated by Django 6.0.2 on 2026-02-05 09:45

import apps.project.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_alter_stuctsortdata_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicHardwareTable',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dynamic_hardware', serialize=False, to='project.project', verbose_name='关联项目')),
                ('table', models.JSONField(default=apps.project.models.default_json_value, help_text='储存表格二维数组', verbose_name='储存表格二维数组')),
            ],
            options={
                'verbose_name': '动态硬件项表',
                'verbose_name_plural': '动态硬件项表',
                'db_table': 'project_dynamic_hardware',
            },
        ),
        migrations.CreateModel(
            name='DynamicSoftTable',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dynamic_soft_item', serialize=False, to='project.project', verbose_name='关联项目')),
                ('table', models.JSONField(default=apps.project.models.default_json_value, help_text='储存表格二维数组', verbose_name='储存表格二维数组')),
            ],
            options={
                'verbose_name': '动态软件项表',
                'verbose_name_plural': '动态软件项表',
                'db_table': 'project_dynamic_soft_item',
            },
        ),
        migrations.CreateModel(
            name='StaticSoftHardware',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='static_hardware', serialize=False, to='project.project', verbose_name='关联项目')),
                ('table', models.JSONField(default=apps.project.models.default_json_value, help_text='储存表格二维数组', verbose_name='储存表格二维数组')),
            ],
            options={
                'verbose_name': '静态硬件项表',
                'verbose_name_plural': '静态硬件项表',
                'db_table': 'project_static_hardware',
            },
        ),
        migrations.CreateModel(
            name='StaticSoftItem',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='static_soft_item', serialize=False, to='project.project', verbose_name='关联项目')),
                ('table', models.JSONField(default=apps.project.models.default_json_value, help_text='储存表格二维数组', verbose_name='储存表格二维数组')),
            ],
            options={
                'verbose_name': '静态软件项表',
                'verbose_name_plural': '静态软件项表',
                'db_table': 'project_static_soft_item',
            },
        ),
    ]
