# Generated by Django 6.0.2 on 2026-02-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_dynamichardwaretable_dynamicsofttable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamichardwaretable',
            name='fontnote',
            field=models.CharField(default='', help_text='数据的题注说明', max_length=256, null=True, verbose_name='题注'),
        ),
        migrations.AddField(
            model_name='dynamicsofttable',
            name='fontnote',
            field=models.CharField(default='', help_text='数据的题注说明', max_length=256, null=True, verbose_name='题注'),
        ),
        migrations.AddField(
            model_name='staticsofthardware',
            name='fontnote',
            field=models.CharField(default='', help_text='数据的题注说明', max_length=256, null=True, verbose_name='题注'),
        ),
        migrations.AddField(
            model_name='staticsoftitem',
            name='fontnote',
            field=models.CharField(default='', help_text='数据的题注说明', max_length=256, null=True, verbose_name='题注'),
        ),
    ]
