# Generated by Django 6.0.2 on 2026-02-05 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_dynamichardwaretable_fontnote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDynamicDescription',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='dynamic_des', serialize=False, to='project.project', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '动态环境描述',
                'verbose_name_plural': '动态环境描述',
                'db_table': 'project_dynamic_description',
            },
        ),
        migrations.AddField(
            model_name='stuctsortdata',
            name='dynamic_description',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_schemas', to='project.projectdynamicdescription', verbose_name='所属动态环境描述'),
        ),
    ]
