# Generated by Django 6.0.2 on 2026-02-06 13:56

import apps.project.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_evaluatedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvAnalysis',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='env_analysis', serialize=False, to='project.project', verbose_name='关联项目')),
                ('table', models.JSONField(default=apps.project.models.default_json_value, help_text='储存表格二维数组', verbose_name='储存表格二维数组')),
                ('fontnote', models.CharField(default='', help_text='数据的题注说明', max_length=256, null=True, verbose_name='题注')),
                ('description', models.CharField(default='', max_length=1024, null=True, verbose_name='差异性分析文字')),
            ],
            options={
                'verbose_name': '环境差异性分析表',
                'verbose_name_plural': '环境差异性分析表',
                'db_table': 'project_env_analysis',
            },
        ),
    ]
