# Generated by Django 6.0.2 on 2026-02-06 16:05

import apps.project.models
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_envanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluenceArea',
            fields=[
                ('project', models.OneToOneField(db_constraint=False, help_text='关联项目', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='influence', serialize=False, to='project.round', verbose_name='关联项目')),
            ],
            options={
                'verbose_name': '影响域分析',
                'verbose_name_plural': '影响域分析',
                'db_table': 'round_influence_area',
            },
        ),
        migrations.CreateModel(
            name='InfluenceItem',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('change_type', models.CharField(default='', help_text='更改类型', max_length=256, null=True, verbose_name='更改类型')),
                ('change_des', tinymce.models.HTMLField(blank=True, null=True, verbose_name='更改内容描述')),
                ('effect_cases', models.JSONField(default=apps.project.models.create_list, verbose_name='影响的用例key数组')),
                ('influence', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influence_items', to='project.influencearea', verbose_name='所属影响域分析')),
            ],
            options={
                'verbose_name': '影响域分析 - 行数据',
                'verbose_name_plural': '影响域分析 - 行数据',
                'db_table': 'influence_item',
            },
        ),
    ]
