# Generated by Django 6.0.2 on 2026-02-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_influencearea_influenceitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='influencearea',
            old_name='project',
            new_name='round',
        ),
    ]
