# Generated by Django 6.0.2 on 2026-02-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_rename_project_influencearea_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='influenceitem',
            name='change_influ',
            field=models.TextField(default='', help_text='影响域分析', max_length=2048, null=True, verbose_name='影响域分析'),
        ),
    ]
