# Generated by Django 6.0.4 on 2026-04-17 13:57

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_influenceitem_change_influ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='devplant',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='开发环境', null=True, verbose_name='开发环境'),
        ),
        migrations.AlterField(
            model_name='project',
            name='runtime',
            field=models.JSONField(blank=True, default=apps.project.models.create_list, help_text='运行环境', null=True, verbose_name='运行环境'),
        ),
    ]
