# Generated by Django 6.0.4 on 2026-04-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_alter_project_devplant_alter_project_runtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdemand',
            name='adequacy',
            field=models.CharField(blank=True, help_text='充分条件', max_length=2048, null=True, verbose_name='充分条件'),
        ),
    ]
