# Generated by Django 6.0.4 on 2026-04-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_alter_testdemand_adequacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='protocal',
            field=models.CharField(blank=True, default='', help_text='接口数据', max_length=1024, null=True, verbose_name='接口数据'),
        ),
    ]
