# Generated by Django 6.0.4 on 2026-04-21 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_alter_design_protocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='protocal',
        ),
        migrations.RemoveField(
            model_name='design',
            name='to',
        ),
        migrations.RemoveField(
            model_name='design',
            name='type',
        ),
        migrations.AlterField(
            model_name='design',
            name='source',
            field=models.CharField(blank=True, default='', help_text='接口来源', max_length=256, null=True, verbose_name='接口来源'),
        ),
        migrations.CreateModel(
            name='JKDesignInfo',
            fields=[
                ('id', models.BigAutoField(help_text='Id', primary_key=True, serialize=False, verbose_name='Id')),
                ('remark', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('update_datetime', models.DateField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('sort', models.IntegerField(blank=True, default=1, help_text='显示排序', null=True, verbose_name='显示排序')),
                ('direction', models.CharField(choices=[('forward', '正向'), ('reverse', '反向')], max_length=10, verbose_name='方向')),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='接口描述')),
                ('source', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='来源')),
                ('destination', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='目的地')),
                ('jk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jkField', to='project.design', verbose_name='所属接口Design')),
            ],
            options={
                'verbose_name': '接口一个方向的信息',
                'verbose_name_plural': '接口一个方向的信息',
                'unique_together': {('jk', 'direction')},
            },
        ),
    ]
