# Generated by Django 6.0.4 on 2026-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_remove_design_protocal_remove_design_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='source',
        ),
        migrations.AddField(
            model_name='design',
            name='type',
            field=models.CharField(blank=True, default='', help_text='接口类型', max_length=1024, null=True, verbose_name='接口类型'),
        ),
        migrations.AlterField(
            model_name='jkdesigninfo',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='接口描述'),
        ),
        migrations.AlterField(
            model_name='jkdesigninfo',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='目的地'),
        ),
        migrations.AlterField(
            model_name='jkdesigninfo',
            name='source',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='来源'),
        ),
    ]
