# Generated by Django 6.0.4 on 2026-04-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_remove_design_source_design_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='is_bidirectional',
            field=models.BooleanField(default=False, verbose_name='是否双向'),
        ),
    ]
