# Generated by Django 6.0.4 on 2026-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_design_is_bidirectional'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamichardwaretable',
            name='rounds_map',
            field=models.JSONField(blank=True, default=list, help_text='二维数组，每个内层数组是该行选中的轮次索引（字符串）', verbose_name='轮次数据'),
        ),
        migrations.AddField(
            model_name='dynamicsofttable',
            name='rounds_map',
            field=models.JSONField(blank=True, default=list, help_text='二维数组，每个内层数组是该行选中的轮次索引（字符串）', verbose_name='轮次数据'),
        ),
        migrations.AddField(
            model_name='evaluatedata',
            name='rounds_map',
            field=models.JSONField(blank=True, default=list, help_text='二维数组，每个内层数组是该行选中的轮次索引（字符串）', verbose_name='轮次数据'),
        ),
        migrations.AddField(
            model_name='staticsofthardware',
            name='rounds_map',
            field=models.JSONField(blank=True, default=list, help_text='二维数组，每个内层数组是该行选中的轮次索引（字符串）', verbose_name='轮次数据'),
        ),
        migrations.AlterField(
            model_name='project',
            name='beginTime',
            field=models.DateField(blank=True, help_text='开始时间', null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endTime',
            field=models.DateField(blank=True, help_text='结束时间', null=True, verbose_name='结束时间'),
        ),
    ]
