# Generated by Django 6.0.4 on 2026-04-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_dynamichardwaretable_rounds_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticsoftitem',
            name='rounds_map',
            field=models.JSONField(blank=True, default=list, help_text='二维数组，每个内层数组是该行选中的轮次索引（字符串）', verbose_name='轮次数据'),
        ),
    ]
